/**
 * Pure plan-builder for the legacy `ServiceVisit.poolId` → `ServiceVisitPool`
 * join-row backfill (card: "[Multi-Body] Data-backfill migration script").
 *
 * Pure: no I/O, no `server-only`, no Prisma runtime — only type-only imports
 * from `@/generated/prisma/client` so DIP holds and the module is unit-testable
 * in vitest. The executor (`scripts/backfill-service-visit-pools.ts`) feeds it
 * rows loaded from the DB and applies the plan it returns.
 *
 * Invariant the builder preserves: a join row's `companyId` is ALWAYS derived
 * from its pool's `companyId` (`poolCompanyIdByPoolId`) — it can never drift.
 * Orphan visits (pool missing from the map) are collected, never guessed.
 */
import type {
  ChemicalAdded,
  ServiceVisit,
  ServiceVisitPool,
  WaterReading,
} from "@/generated/prisma/client";

/** A legacy visit as loaded for backfill (legacy `poolId` + created time). */
export type BackfillVisitRow = Pick<ServiceVisit, "id" | "poolId" | "createdAt">;

/** An existing join row, loaded so partial-run healing can reuse its id. */
export type ExistingJoinRow = Pick<
  ServiceVisitPool,
  "id" | "serviceVisitId" | "poolId"
>;

/** A legacy child row (reading or chemical) keyed by its `visitId`. */
export type BackfillChildRow =
  | Pick<WaterReading, "id" | "visitId">
  | Pick<ChemicalAdded, "id" | "visitId">;

export interface BackfillJoinToCreate {
  serviceVisitId: string;
  poolId: string;
  companyId: string;
  createdAt: Date;
}

/**
 * A batch of child rows (readings or chemicals) to point at one join row.
 * `joinId` is set when the visit already has a join row (partial-run healing —
 * a crash between join-create and child-update self-heals on re-run). `null`
 * when the visit's join is created by this run: its id is generated by the DB
 * during `createMany`, so the executor resolves it after creating the joins.
 */
export interface BackfillChildBatch {
  serviceVisitId: string;
  joinId: string | null;
  ids: string[];
}

export interface ServiceVisitPoolBackfillPlan {
  /** Join rows to create (id generated by the DB cuid). */
  joinsToCreate: BackfillJoinToCreate[];
  /** Readings (`serviceVisitPoolId: null`) to point at their visit's join. */
  readingsToUpdate: BackfillChildBatch[];
  /** Chemicals (`serviceVisitPoolId: null`) to point at their visit's join. */
  chemicalsToUpdate: BackfillChildBatch[];
  /** Visits whose pool is missing from `poolCompanyIdByPoolId` — never guessed. */
  orphanVisits: Array<{ id: string; poolId: string }>;
  /** Visits that already have a join row — not duplicated. */
  skippedVisits: Array<{ id: string; poolId: string }>;
  summary: {
    visits: number;
    joinsToCreate: number;
    readingsToUpdate: number;
    chemicalsToUpdate: number;
    orphanVisits: number;
    skippedVisits: number;
  };
}

export interface ServiceVisitPoolBackfillInput {
  visits: BackfillVisitRow[];
  /** poolId → companyId, loaded from `Pool`. */
  poolCompanyIdByPoolId: Record<string, string>;
  existingJoins: ExistingJoinRow[];
  unbackfilledReadings: BackfillChildRow[];
  unbackfilledChemicals: BackfillChildRow[];
}export function buildServiceVisitPoolBackfillPlan(
  input: ServiceVisitPoolBackfillInput,
): ServiceVisitPoolBackfillPlan {
  const {
    visits,
    poolCompanyIdByPoolId,
    existingJoins,
    unbackfilledReadings,
    unbackfilledChemicals,
  } = input;

  const joinsToCreate: BackfillJoinToCreate[] = [];
  const orphanVisits: Array<{ id: string; poolId: string }> = [];
  const skippedVisits: Array<{ id: string; poolId: string }> = [];

  // visitId → joinId for child mapping. `null` means the join is created this
  // run (id unknown until the DB cuid is generated).
  const joinIdByVisit = new Map<string, string | null>();

  for (const visit of visits) {
    const companyId = poolCompanyIdByPoolId[visit.poolId];
    if (companyId === undefined) {
      orphanVisits.push({ id: visit.id, poolId: visit.poolId });
      continue;
    }

    const existing = existingJoins.find((join) => join.serviceVisitId === visit.id);
    if (existing) {
      skippedVisits.push({ id: visit.id, poolId: visit.poolId });
      joinIdByVisit.set(visit.id, existing.id);
      continue;
    }

    joinsToCreate.push({
      serviceVisitId: visit.id,
      poolId: visit.poolId,
      companyId,
      createdAt: visit.createdAt,
    });
    joinIdByVisit.set(visit.id, null);
  }

  const groupChildren = (rows: BackfillChildRow[]): BackfillChildBatch[] => {
    const byVisit = new Map<string, string[]>();
    for (const row of rows) {
      const ids = byVisit.get(row.visitId) ?? [];
      ids.push(row.id);
      byVisit.set(row.visitId, ids);
    }

    const batches: BackfillChildBatch[] = [];
    for (const [visitId, ids] of byVisit) {
      if (!joinIdByVisit.has(visitId)) continue;
      batches.push({
        serviceVisitId: visitId,
        joinId: joinIdByVisit.get(visitId) ?? null,
        ids,
      });
    }
    return batches;
  };

  const readingsToUpdate = groupChildren(unbackfilledReadings);
  const chemicalsToUpdate = groupChildren(unbackfilledChemicals);

  return {
    joinsToCreate,
    readingsToUpdate,
    chemicalsToUpdate,
    orphanVisits,
    skippedVisits,
    summary: {
      visits: visits.length,
      joinsToCreate: joinsToCreate.length,
      readingsToUpdate: readingsToUpdate.reduce((n, b) => n + b.ids.length, 0),
      chemicalsToUpdate: chemicalsToUpdate.reduce((n, b) => n + b.ids.length, 0),
      orphanVisits: orphanVisits.length,
      skippedVisits: skippedVisits.length,
    },
  };
}
